forem/DEV-ios

DEV.xcodeproj/project.pbxproj, README.md
Since contributors will most likely be adding the same build paths, I added the run script to the build phases. This removes a step for setup and allows for tighter management of dependencies should some be added or removed.
People prefer to manage repos differently so please comment if you disagree with these changes!
=> Adding Carthage run script

DEV/Base.lproj/Main.storyboard
Just want to maintain the storyboard warning free so that maintaining as we progress is easier.
=> Fixed autolayout warning on Search field in Search scene

DEV/AppDelegate.swift, DEV/Base.lproj/Main.storyboard, DEV/ConnectViewController.swift, DEV/FirstViewController.swift, DEV/NotificationsViewController.swift, DEV/SearchViewController.swift
This PR rips out some of the changes which resulted in the problems with issue #12.
It also gives a custom user agent on the /connect tab so the web app can adjust its styling. This is probably something we'll want across all views, but this was immediately actionable here.
=> Go back to non-DRY implementation for tab bar and other small changes

Cartfile, Cartfile.resolved, DEV.xcodeproj/project.pbxproj, DEV/FirstViewController.swift, DEV/Model/User.swift
Since the Alamofire framework is already being used I found it most fitting to use the AlamofireImage framework for this task. 
The solution is fairly straight forward, I added a new `profileImage` property to the `User` object as an alias for `profile_image_90`. After mapping the property I piggy back off of `updateProfileViewController()` to fetch the image, scale it, and create a new tab item for the profile tab.
=> Retrieving User's Profile Image

DEV/ConnectViewController.swift, DEV/FirstViewController.swift, DEV/NotificationsViewController.swift, DEV/ProfileViewController.swift, DEV/SearchViewController.swift
The observer now watches for a change in the `canGoBack` property. This allows for back button management to occur only when that property changes, which should fix #38. 
If the changes are approved I'll propagate to the remaining view controllers.
=> Improving Back Button

DEV/Login/LoginViewController.swift
To Fix https://github.com/thepracticaldev/DEV-ios/issues/46
Currently users are able to navigate the website without logging in by navigating from the footer on the login page. 
This PR hides the footer to prevent this behaviour
=> Hide footer on login page so users cannot navigate without logging in

DEV/AppDelegate.swift, DEV/Constants/URLConstants.swift, DEV/FirstViewController.swift, DEV/Info.plist
Deep link with the URLs received with scheme devto:// instead of https://. Needs support from webpage end to provide open in app for articles. Details of webpage changes needed are mentioned in the issue linked below.
Universal links are not a part of this implementation.
Issue: https://github.com/thepracticaldev/DEV-ios/issues/40
=> Issue:40 - Implemented deep link support

DEV-Simple.xcodeproj/project.pbxproj, DEV-Simple/ViewController.swift, DEV-SimpleTests/ViewControllerTests.swift, DEV-SimpleTests/test.html
Refactored decidePolicyForNavigationAction function to remove force unwraps and hopefully make intent clearer
=> Refactor decidePolicyForNavigationAction

DEV-Simple/AppDelegate.swift
This was already mostly built in to deal with notifications. This simply adds the listener for universal link context.
Closes #99
=> Add universal link functionality

.swiftlint.yml, DEV-Simple/AppDelegate.swift, DEV-Simple/BrowserViewController.swift, DEV-Simple/ViewController.swift, DEV-SimpleTests/ViewControllerTests.swift
In this PR I have updated the `.swiftlint.yml` file to look at the correct new folder (From DEV -> To DEV-Simple) also added to the `.swiftlint.yml` to ignore the Carthage directory, also for the ones using Xcode the reporter has been change from JSON to Xcode. to able to see the warnings. 
With swiftLint working again a did a formatting with the linter recommendations, with this preliminary setup with can discuss the use of custom rules for styling in the development of the app.
Also I did a change for some memory leaks with strong self references in closures.
Any questions I'm glad to respond.
- Erick
=> Swiftlint config and linter corrections with minor improvements.

DEV-Simple/Info.plist
The only difference here from the previous project is I'm using `$(PRODUCT_NAME)` instead of defining one. If you it should be different, let me know and I'll change it!
Fixes #106
=> Adding CFBundleURLTypes from previous project

Cartfile, Cartfile.resolved, DEV-Simple.xcodeproj/project.pbxproj, DEV-Simple/AppDelegate.swift, DEV-Simple/NetworkReachability.swift, DEV-Simple/ViewController.swift
Had some code laying around and plugged it in to get network detection going and added the [NotificationBanner](https://github.com/Daltron/NotificationBanner) library for displaying a banner. Currently the only banner being displayed is when there is no network connection at all, but I plan on expanding the logic to display for various situations with corresponding messages.
This code is kind of old so I'm looking at using the [Reachability.swift](https://github.com/ashleymills/Reachability.swift) library which looks pretty similar but more refined.
Closes #103
=> Network Reachability

DEV-Simple.xcodeproj/project.pbxproj
Previously there were two "Run Script" phases making it unclear what each one does. I've named them so that the phases don't need to be expanded to figure out what they do, and this also helps if more scripts are added in the future.
=> Renaming Build Phase Scripts

DEV-Simple.xcodeproj/project.pbxproj, DEV-Simple/Base.lproj/Main.storyboard, DEV-Simple/BrowserViewController.swift, DEV-Simple/Globals.swift, DEV-Simple/ViewController.swift
This PR resolves the Feature Request in #115 adding a Loading Spinner for the first time a app opens or when the app opens from a push notification
=> Feature 115 loading spinner

DEV-Simple/ViewController.swift
Moved the NotificationCenter observer as recommended on the framework [instructions](https://github.com/ashleymills/Reachability.swift)  
Please check
=> Reachability changes

DEV-Simple/storyboards/Base.lproj/Main.storyboard, DEV-Simple/views/ViewController.swift
This PR address issue https://github.com/thepracticaldev/DEV-ios/issues/164
where the only way to refresh the current page is to do a pull-refresh. 
We are giving users an additional way to refresh the page by adding a native refresh button to the navigation bar as shown here:
I only tested this feature manually, but if you have any feedback on whether or how I should add a unit test or UI test, I welcome that. Thanks!
=> Add Native Refresh Button To Navigation Bar

Cartfile.resolved, DEV-Simple/views/ViewController.swift
This PR address issue #180, setting background color manually is not needed, because status bar color is same as ViewController.view backgroundColor, tested on all supported iOS versions (11, 12, 13)
=> [#180] App crashes when DarkTheme enabled on iOS 13

DEV-Simple/views/ViewController.swift
Fix bug where conflicts occur when users have the dark mode set for the OS and the light version of the app in their DEV settings.
#205
=> [205] Fix colors in safe area

DEV-Simple.xcodeproj/project.pbxproj
It adds Target Membership assignment for the entitlements file. [Relevant SO discussion](https://stackoverflow.com/questions/41368685/xcode-8-2-cannot-set-entitlements-membership)
**Before:**
**Fix:**
(add the entitlements file to "Copy Bundle Resources" in the main Target Build Phases)
**After:**
It might (hopefully) help us fix #209
=> Adds Target Membership to entitlements file

DEV-Simple/core/MediaManager.swift
When the audio player is terminated in the app the locked screen controls from `MPRemoteCommandCenter` were not removed. This means the audio player was terminated but if a user were to click on "play" using these controls the audio would start audio playback, without the audio player controls available within the app.
Luckily one line fixes this when terminating the Podcast player.
=> Removes locked screen controls when audio player is terminated

DEV-Simple.xcodeproj/project.pbxproj, DEV-Simple/Extensions/Bundle+Extensions.swift, DEV-Simple/core/MediaManager.swift
The locked screen controls when playing a Podcast were showing the App Icon (poorly) for all Podcasts. 
This PR implements the code necessary to handle a URL sent in the `metadata` message. If no URL is received (or an invalid URL for that matter) the behavior is the same as before but slightly better.
Implements the iOS side for #218
=> Native bridge metadata message support for Podcast Image URL

DEV-Simple/storyboards/Base.lproj/Main.storyboard, DEV-Simple/views/ViewController.swift
With Crayons out in production these changes make sure the safe area and toolbar are displayed accordingly.
[Crayons'ifizing Header](https://github.com/thepracticaldev/dev.to/pull/6780)
_Feed before_ 
_Browser view before_ 
_Dark Feed before_ 
_Feed after_
_Browser view after_
_Dark Feed after_
=> Minor tweaks for safe area & toolbar coloring

DEV-Simple.xcodeproj/project.pbxproj, DEV-Simple/Extensions/URL+Extensions.swift, DEV-Simple/core/MediaManager.swift, DEV-Simple/views/ViewController.swift
Since [7303](https://github.com/thepracticaldev/dev.to/pull/7303) was merged we will get relative paths for Podcast metadata when working on development. The PR handles relative paths in a separate function.
=> Better handling of podcast metadata for locked screen artwork

DEV-Simple/core/MediaManager.swift
This PR changes a few things in the way Podcasts are being played:
- Adds the `init` message to enhance the experience when switching between Podcasts: Shows `initializing...` label in the UI controls instead of badly formatted time stamps.
- Fixes a bug that happened when playing a Podcast Episode and the user wants to play a different one, they would need to terminate (close with `x` button) before being able to play the next one: They can just `play` any episode, no matter if they were previously listening to another one.
- Adds support for `volume` message. iPhones don't need this because they only have the mute capability, but iPads may use this feature (hover will present the volume slider)
=> Adds init msg and enhancements for the UX of the Podcast Player

DEV-Simple/views/ViewController.swift
Added a check for the Ten X dark theme.
I noticed there is quite a bit of the project was refactored in #229 so once that is merged I will work on more proper theming capability.
Closes #230
=> Handle Ten X Theme

DEV-Simple/core/MediaManager.swift
Hello.
Thank you for DEV-ios.
I did a small refactoring in MediaManager.swift.
=> A small refactoring
