- .gitignore
- .travis.yml
- DEV.xcodeproj/xcshareddata/xcschemes/DEV.xcscheme
- Gemfile
- README.md
- fastlane/Appfile
- fastlane/Fastfile
This is just the initial work at getting CI setup so right now it only runs unit tests. More on the way!
**NOTE:** In order for this to work, @benhalpern needs to connect Travis. Once that's done the badge needs to be changed so it's no longer pointing at my Travis pipeline.
> Travis and Fastlane Setup

- DEV.xcodeproj/project.pbxproj
- DEV/ConnectViewController.swift
- DEV/Constants/URLConstants.swift
- DEV/DashboardViewController.swift
- DEV/FirstViewController.swift
- DEV/NewArticleViewController.swift
- DEV/NotificationsViewController.swift
- DEV/ProfileViewController.swift
- DEV/SearchViewController.swift
This is kind of small refactoring for current implementation by introducing a constant file that contains the url that will be used by each view controller, 
Feedbacks are really appreciated,
> Introduce URL Constant and apply on each view controller 

- DEV.xcodeproj/project.pbxproj
- DEV/Base.lproj/Main.storyboard
- DEV/Extensions/UIColor+DevColor.swift
- DEV/NotificationsViewController.swift
- DEV/ViewController/DevWebView/DevWebViewController.swift
- DEV/ViewController/DevWebView/DevWebViewLoadable.swift
Hi @benhalpern 
I am trying to propose custom view controller to handle web view from current state of this project, by introducing `DevWebViewController`
The reason behind that because i saw there are a lot of duplicated code for each of view controller that is actually doing the same thing,
That view controller basically just a generic view controller that will manage the web view, 
In this pull request i only changed `NotificationViewController`
By extending DevWebViewController, each of view controller only need to specify `webURL` so that we will have simpler and clean view controller code. 
if you are fine with that, i will try slowly changed the others too 
Looking forward for your feedback 
Thanks
> Propose Custom WebViewController 

- DEV/Base.lproj/Main.storyboard
Small pull request to center the activity indicator with respect to the safe area for all devices.
Webviews constraints also need to be updated - will try to work on those this weekend
> Updated activity indicator constraints

- .gitignore
- .travis.yml
Pretty minor but fixes the issues with Brew/SwiftLint so the build doesn't fail. Lint results aren't being displayed yet but that can be added with Danger (I think, still learning some of this DevOps stuff). 
@benhalpern still needs to create a Travis account and point a build at this repo. Since the files are in place, no other work should be necessary 😃
> Updating Travis and Fastlane

- DEV.xcodeproj/project.pbxproj
- DEV/Base.lproj/Main.storyboard
- DEV/ConnectViewController.swift
- DEV/Constants/URLConstants.swift
- DEV/FirstViewController.swift
- DEV/Info.plist
- DEV/Login/Base.lproj/Login.storyboard
- DEV/Login/LoginCoordinator.swift
- DEV/Login/LoginViewContoller.swift
- DEV/Login/LoginViewController.swift
- DEV/Model/User.swift
- DEV/NotificationsViewController.swift
- DEV/ProfileViewController.swift
- DEV/SearchViewController.swift
- DEV/ViewController/DevWebView/CanReload.swift
First attempt at setting up login so all users of the app need to log in
LoginViewController set to the initial view controller
If login is successful then redirect to main tab bar controller
> Set up login

- DEV/Base.lproj/Main.storyboard
- DEV/SearchViewController.swift
- README.md
Minor improvements to the search input interactions on the search controller.
- Clear search input on return to root page
- Toggle keyboard on view appear, dismiss on user interact
- Enlarge search bar
> Update search controller

- .travis.yml
- DEV.xcodeproj/project.pbxproj
- DEV/AppDelegate.swift
- DEV/ViewController/DevWebView/DevWebViewController.swift
I used the built in Xcode migration tool. AFAIK nothing broke, the app still builds/runs, and the tests are passed
_NB : I'm using Xcode 10 on macOS Mojave_
> Migrated to Swift 4.2 with the migration tool

- DEV/Base.lproj/Main.storyboard
There is a gap between the right edge on home screen and the screen. This PR fixes it by updating the storyboard.
> Constraint fix for iPhone XS Max

- DEV/FirstViewController.swift
Adjust a bit of the logic to get the tabs refreshing appropriately.
> Adjust tab refresh logic

- DEV.xcodeproj/project.pbxproj
- DEV/Info.plist
I _think_ this is all good stuff. Stuff I did for previously pushing to Testflight.
Let me know if there's a problem with this. Otherwise I'll merge shortly.
> Change PRODUCT_BUNDLE_IDENTIFIER and other small things

- DEV.xcodeproj/project.pbxproj
- DEV/ConnectViewController.swift
- DEV/DashboardViewController.swift
- DEV/FirstViewController.swift
- DEV/NewArticleViewController.swift
- DEV/NotificationsViewController.swift
- DEV/ProfileViewController.swift
- DEV/SearchViewController.swift
- DEV/ViewController/DevWebView/BaseWebViewController.swift
With the addition of the new base view controller class, also fixes the scroll indicator issue from #67
> Adds a new BaseWebViewController and fixes a scroll indicator issue

- DEV-Simple/Info.plist
- DEV-Simple/ViewController.swift
Tiny change and bumped version. Basically side-effect from submitting to the app store again.
Not much to see here.
> Minute change/bump version

- Gemfile
- fastlane/Appfile
- fastlane/Fastfile
Looks like Travis is failing due to missing Fastlane files. Hopefully this PR corrects that issue.
Update: Travis is fixed!
> Restoring Fastlane

- DEV-Simple/Base.lproj/Main.storyboard
- DEV-Simple/NetworkReachability.swift
- DEV-Simple/ViewController.swift
Navigation border color problems fix as described in #122
> Navigation color border

- DEV-Simple/Info.plist
- DEV-Simple/views/ViewController.swift
Listen for night mode indicator from web view and adjust shell as appropriate
> Add night mode compatability

- DEV-Simple/views/ViewController.swift
Fixes #137 but from what I've read on Stack Overflow `webkit-playsinline` also needs to be added as an attribute of the `<video>` tag.
> Allow Inline Media

- .github/PULL_REQUEST_TEMPLATE.md
- CODE_OF_CONDUCT.md
Added a Code Of Conduct similar to the COC on the Dev.to Web App as suggested in #178
> Code of conduct, Fixes #178

- .github/PULL_REQUEST_TEMPLATE.md
Added a PR template PR template to make it easier for contributors and maintainers to publish and view Pull Requests as suggested in Issue #174
> added PR template, Fixes #174

- DEV-Simple.xcodeproj/project.pbxproj
- README.md
Upgrading the project to Swift 5
> Migration to Swift 5

- DEV-Simple.xcodeproj/project.pbxproj
- DEV-Simple.xcodeproj/xcshareddata/xcschemes/DEV-Simple-Local.xcscheme
- DEV-Simple/Info.plist
- DEV-Simple/core/AppDelegate.swift
- DEV-Simple/core/MediaManager.swift
- DEV-Simple/core/PodcastManager.swift
- DEV-Simple/views/ViewController.swift
- DEV-SimpleUITests/Info.plist
This PR works on handling messages sent from javascript to trigger native AVPlayer playback of Podcasts. [This is the PR](https://github.com/thepracticaldev/dev.to/pull/6035) with the web updates required to make this feature work.
- #203 details the current audio issue
- [thepracticaldev/dev.to PR](https://github.com/thepracticaldev/dev.to/pull/6035)
> Native audio play

- DEV-Simple.xcodeproj/project.pbxproj
- DEV-Simple/Info.plist
> 1.4.0 version bump

- DEV-Simple/core/MediaManager.swift
This persists selected playback rate between podcast plays.
Fixes #216
> Keep track of playback rate between plays

- DEV-Simple/core/MediaManager.swift
This adds buttons for skip ahead and back 15 seconds. Currently we have useless "next track" buttons.
Fixes #215
> Add skip ahead/buttons to command center

- DEV-Simple.xcodeproj/project.pbxproj
> Bump marketing version

- DEV-Simple.xcodeproj/project.pbxproj
Version bump to release some Podcast Player enhancements
> Version bump to 1.4.3

- Cartfile.resolved
- DEV-Simple.xcodeproj/project.pbxproj
- DEV-Simple/AppDelegate.swift
- DEV-Simple/ViewController.swift
> Minor cleanup
